{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required "name is required" .Values.name }}
spec:
  accessModes:
  - {{ ternary "ReadWriteMany" "ReadWriteOnce" .Values.useFileShare }}
  resources:
    requests:
      storage: {{ required "disk.capacity is required" .Values.disk.capacity }}
  storageClassName: {{ ternary "azurefile-csi" "managed-csi" .Values.useFileShare }}
  volumeName: {{ required "name is required" .Values.name }}
{{- end }}