apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convertx
  template:
    metadata:
      labels:
        app: convertx
    spec:
      containers:
      - name: convertx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
          protocol: TCP
        environment:
        - name: JWT_SECRET
          value: {{ .Values.jwtSecret | quote }}