apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: convertx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: convertx-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    nginx.ingress.kubernetes.io/proxy-body-size: {{ required "maxSize is required" .Values.maxSize | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ required "ingress.host is required" .Values.ingress.host | quote }}
      secretName: convertx-tls
  rules:
  - host: {{ required "ingress.host is required" .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: convertx
            port:
              number: 80
