apiVersion: apps/v1
kind: Deployment
metadata:
  name: crafty-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crafty-proxy
  template:
    metadata:
      labels:
        app: crafty-proxy
    spec:
      containers:
      - name: caddy
        image: caddy:latest
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
      volumes:
      - name: caddy-config
        configMap:
          name: crafty-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crafty-proxy-config
data:
  Caddyfile: |
    :80 {
      reverse_proxy 192.168.68.126:8443 {
        trusted_proxies private_ranges
        transport http {
          tls
          tls_insecure_skip_verify
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: crafty-proxy
spec:
  selector:
    app: crafty-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crafty-migration
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minecraft.mattjeanes.com
      secretName: crafty-tls
  rules:
  - host: minecraft.mattjeanes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crafty-proxy
            port:
              number: 80
