apiVersion: apps/v1
kind: Deployment
metadata:
  name: octoprint-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octoprint-proxy
  template:
    metadata:
      labels:
        app: octoprint-proxy
    spec:
      containers:
      - name: caddy
        image: caddy:latest
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
      volumes:
      - name: caddy-config
        configMap:
          name: octoprint-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: octoprint-proxy-config
data:
  Caddyfile: |
    :80 {
      basicauth {
        matt JDJhJDE0JGtiLkplZ295YTdJV2pIMzRkYVlTWmVvNmxmbGlaZnNvaC9FWk5ZWjU4MzNCZjgwOEtDOUdt
      }
      reverse_proxy 192.168.68.68:80 {
        trusted_proxies private_ranges
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: octoprint-proxy
spec:
  selector:
    app: octoprint-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octoprint-migration
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - octoprint.mattjeanes.com
      secretName: octoprint-tls
  rules:
  - host: octoprint.mattjeanes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: octoprint-proxy
            port:
              number: 80
