name: 'Initialize Terraform'
description: 'Sets up Terraform/OpenTofu and initializes the backend'
inputs:
  azureCredentials:
    description: 'Azure credentials'
    required: true
  terraformStorageAccountName:
    description: 'Storage account name for the Terraform backend'
    required: false
    default: 'abyssterraform'
  terraformContainerName:
    description: 'Container name for the Terraform backend'
    required: false
    default: 'terraform'
  terraformStateKey:
    description: 'Key for the Terraform backend'
    required: false
    default: 'terraform.tfstate'
  terraformStorageAccountKey:
    description: 'Access key for the Terraform backend'
    required: true
  workingDirectory:
    description: 'Directory containing Terraform files'
    required: false
    default: 'terraform'

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
      with:
        creds: ${{ inputs.azureCredentials }}

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1

    - name: Terraform Init
      run: tofu init -backend-config="storage_account_name=${{ inputs.terraformStorageAccountName }}" -backend-config="container_name=${{ inputs.terraformContainerName }}" -backend-config="key=${{ inputs.terraformStateKey }}" -backend-config="access_key=${{ inputs.terraformStorageAccountKey }}" -upgrade
      working-directory: ${{ inputs.workingDirectory }}
      shell: bash