enabled: true
image:
  repository: itzg/minecraft-server
  tag: java21@sha256:0c74660d30f289b22fe2c98a31d6dc5975e46ea6d236a69f5ec7a7d124f90f24
  pullPolicy: IfNotPresent
filebrowser:
  image:
    repository: hurlenko/filebrowser
    tag: v2.63.3@sha256:d2cd8ba8b12d8b7fcc77740e9858b45123e02abc60a515a7a72b0323f58880b3
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 50Mi
  username: "" # Set in pipeline
  password: "" # Set in pipeline
dashboard:
  enabled: false
spiget:
  enabled: false
curseforge:
  enabled: false
  apiKey: "" # Set in pipeline
debug: false
timezone: Europe/London
probes:
  enabled: false
metrics:
  enabled: false
serverProperties:
  difficulty: normal
  whitelist: Divided23
  ops: Divided23
  allowFlight: true
  viewDistance: 16
  simulationDistance: 10
rcon:
  password: "" # Set in pipeline
  broadcastToOps: true
ingress:
  host: "" # Set in pipeline