enabled: true
image:
  repository: itzg/minecraft-server
  tag: java21@sha256:7305c165f9667f0f228b467ad8b8fc0e41c8363514100f33a2a055f3b95dad0f
  pullPolicy: IfNotPresent
filebrowser:
  image:
    repository: hurlenko/filebrowser
    tag: v2.62.1@sha256:352a6d9a07f4b4bfd9eceffcb493a14b6cd3d670d6f648e90bb9f8b270736cf2
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 50Mi
  username: "" # Set in pipeline
  password: "" # Set in pipeline
dashboard:
  enabled: false
spiget:
  enabled: false
curseforge:
  enabled: false
  apiKey: "" # Set in pipeline
debug: false
timezone: Europe/London
probes:
  enabled: false
metrics:
  enabled: false
serverProperties:
  difficulty: normal
  whitelist: Divided23
  ops: Divided23
  allowFlight: true
  viewDistance: 16
  simulationDistance: 10
rcon:
  password: "" # Set in pipeline
  broadcastToOps: true
ingress:
  host: "" # Set in pipeline