enabled: true
image:
  repository: itzg/minecraft-server
  tag: java21@sha256:55b69486b933f34fc8aa97fccc2fd428d640f914d8cbe313607ae9fb6f4689bc
  pullPolicy: IfNotPresent
filebrowser:
  image:
    repository: hurlenko/filebrowser
    tag: v2.63.15@sha256:3c26f9682fa6023e6e86adbe25826b6ce5dcc3e5f86b0300afd667afed1de98b
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 50Mi
  username: "" # Set in pipeline
  password: "" # Set in pipeline
dashboard:
  enabled: false
spiget:
  enabled: false
curseforge:
  enabled: false
  apiKey: "" # Set in pipeline
debug: false
timezone: Europe/London
probes:
  enabled: false
metrics:
  enabled: false
serverProperties:
  difficulty: normal
  whitelist: Divided23
  ops: Divided23
  allowFlight: true
  viewDistance: 16
  simulationDistance: 10
rcon:
  password: "" # Set in pipeline
  broadcastToOps: true
ingress:
  host: "" # Set in pipeline