memory: 2G
version: 1.21.8
type: PAPER
hostPort: 25575
dashboard:
  enabled: true
  url: https://grafana.amyjeanes.com/public-dashboards/0ebe4d51ecbc4a9b9238000cc5ebdbc8
spiget:
  enabled: true
  resources:
  - 83557 # https://www.spigotmc.org/resources/bluemap.83557/
  - 81534 # https://www.spigotmc.org/resources/chunky.81534/
  - 84278 # https://www.spigotmc.org/resources/chunkyborder.84278/
  - 122574 # https://www.spigotmc.org/resources/1-21-1-21-5-restartar-discord-notifications.122574/
  # - 36618 # https://www.spigotmc.org/resources/prometheus-exporter.36618/ (Installed manually as SpigotMC version is out of date)
serverProperties:
  motd: Welcome to The Abyss (Vanilla)!
  seed: "777836211"
volumeClaims:
  server: minecraft-vanilla-server
  world: minecraft-vanilla-world
  bluemap: minecraft-vanilla-bluemap
resources:
  requests:
    cpu: 2
    memory: 2560Mi
  limits:
    memory: 2560Mi