metallb:
  prometheus:
    namespace: monitoring
    serviceAccount: metallb-prometheus
    prometheusRule:
      enabled: true
      addressPoolExhausted:
        enabled: false
      addressPoolUsage:
        enabled: false
    serviceMonitor:
      enabled: true