image:
  repository: ghcr.io/amyjeanes/plex-vaapi
  tag: latest@sha256:675f65b3fba43aeefbca4ffa7cc521c78df6ec7a03d222c3220401293e3c5b60
  pullPolicy: IfNotPresent
initContainer:
  image:
    repository: busybox
    tag: stable@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662
    pullPolicy: IfNotPresent