image:
  repository: ghcr.io/amyjeanes/plex-vaapi
  tag: latest@sha256:3b7c8a3cad5c0fae0fb67a18b2b7a10e7f8bfd94e462418dea4c4536ab188750
  pullPolicy: IfNotPresent
initContainer:
  image:
    repository: busybox
    tag: stable@sha256:73aaf090f3d85aa34ee199857f03fa3a95c8ede2ffd4cc2cdb5b94e566b11662
    pullPolicy: IfNotPresent