image:
  repository: teslamate/teslamate
  tag: 4.2.0@sha256:88f4b0eb20802e4dd8518b31045d2c19ce384bd5c85ae7289a921f5221ea2562
  pullPolicy: IfNotPresent
mqtt:
  enabled: true
  host: "" # set in CLI
  username: "" # set in CLI
  password: "" # set in CLI
database:
  host: postgresql
  name: teslamate
  username: teslamate
  password: "" # set in CLI
encryptionKey: "" # set in CLI
resources:
  requests:
    cpu: 30m
    memory: 350Mi
  limits:
    memory: 350Mi
