image:
  repository: teslamate/teslamate
  tag: 3.1.0@sha256:b7b8b21869d789d043f62b404dd689f55c601ef7d02222e92c0f5d596d0b1044
  pullPolicy: IfNotPresent
mqtt:
  enabled: true
  host: "" # set in CLI
  username: "" # set in CLI
  password: "" # set in CLI
database:
  host: postgresql
  name: teslamate
  username: teslamate
  password: "" # set in CLI
encryptionKey: "" # set in CLI
resources:
  requests:
    cpu: 30m
    memory: 350Mi
  limits:
    memory: 350Mi
