image:
  repository: teslamate/teslamate
  tag: 4.3.0@sha256:516fc9f0a14369f541b1a70ff2f65dd9b57c2e01c1f533b6d43b375445404955
  pullPolicy: IfNotPresent
mqtt:
  enabled: true
  host: "" # set in CLI
  username: "" # set in CLI
  password: "" # set in CLI
database:
  host: postgresql
  name: teslamate
  username: teslamate
  password: "" # set in CLI
encryptionKey: "" # set in CLI
resources:
  requests:
    cpu: 30m
    memory: 350Mi
  limits:
    memory: 350Mi
