apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ required "name is required" .Values.name }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ required "disk.capacity is required" .Values.disk.capacity }}
  local:
    path: {{ .Values.basePath }}/{{ .Values.name }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ required "node is required" .Values.node }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClass.name }}
  volumeMode: Filesystem
