influxdb:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
  influxdb:
    updateStrategy:
      type: Recreate
    resources:
      requests:
        cpu: 10m
        memory: 500Mi
      limits:
        memory: 500Mi
  persistence:
    existingClaim: influxdb