influxdb:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
  influxdb:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: home
    updateStrategy:
      type: Recreate
    resources:
      requests:
        cpu: 10m
        memory: 500Mi
      limits:
        memory: 500Mi
  persistence:
    existingClaim: influxdb