image:
  repository: teamspeaksystems/teamspeak6-server
  tag: 6.0.0-beta10@sha256:8cdf5c5b05865d058622def9eb8d0f2a8a867627ca19f1414298139aefbc1f28
  pullPolicy: IfNotPresent
ports:
  filetransfer: 30033
  serverquery:
    ssh: 10022
    http: 10080
  voice: 9987
persistence:
  existingClaim: teamspeak
resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    memory: 32Mi
