image:
  repository: teamspeaksystems/teamspeak6-server
  tag: 6.0.0-beta13@sha256:bd83056fe34c54e2d72cfb87505b1effa1306f1604462e19ca392dd86fffde36
  pullPolicy: IfNotPresent
ports:
  filetransfer: 30033
  serverquery:
    ssh: 10022
    http: 10080
  voice: 9987
persistence:
  existingClaim: teamspeak
resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    memory: 32Mi
