image:
  repository: teamspeaksystems/teamspeak6-server
  tag: 6.0.0-beta11@sha256:a7073cdda15cee64975201baca8347d1ddde01929fa16ae40394ce45d6ad3333
  pullPolicy: IfNotPresent
ports:
  filetransfer: 30033
  serverquery:
    ssh: 10022
    http: 10080
  voice: 9987
persistence:
  existingClaim: teamspeak
resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    memory: 32Mi
