ingress-nginx:
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 150Mi
    service:
      externalTrafficPolicy: Cluster
      annotations:
        metallb.universe.tf/allow-shared-ip: home
    config:
      annotations-risk-level: Critical
    allowSnippetAnnotations: true