ingress-nginx:
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 150Mi
    service:
      externalTrafficPolicy: Local
    config:
      annotations-risk-level: Critical
    allowSnippetAnnotations: true