ingress-nginx:
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
    hostPort:
      enabled: true
    service:
      type: ClusterIP
    config:
      annotations-risk-level: Critical
      strict-validate-path-type: false
    allowSnippetAnnotations: true
    updateStrategy:
      type: Recreate