apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/server-snippet: return 301 {{ required "redirect is required" .Values.redirect }};
spec:
  tls:
  - hosts:
    - {{ required "host is required" .Values.host }}
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ required "host is required" .Values.host }}