# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml

image:
  repository: sinusbot/docker
  tag: 1.0.0-beta.14-dc94a7c@sha256:c7a4f3cc43939ef18c3d75bf14cf0a6458004a121c5635164ae0e8163d7baf45
  pullPolicy: IfNotPresent
env:
  UID: "1001"
  GID: "1001"
service:
  main:
    ports:
      http:
        port: 8087
persistence:
  sinusbot:
    enabled: true
    type: pvc
    existingClaim: sinusbot
    subPath:
      - mountPath: /opt/sinusbot/data
        path: data
      - mountPath: /opt/sinusbot/scripts
        path: scripts
  data:
    enabled: false
    mountPath: /opt/sinusbot/data
  scripts:
    enabled: false
    mountPath: /opt/sinusbot/scripts
nodeSelector:
  kubernetes.io/arch: amd64
resources:
  requests:
    cpu: 15m
    memory: 200Mi
  limits:
    memory: 200Mi
