apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-direct
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ required "host is required" .Values.host }}
    secretName: hello-world-direct-tls
  rules:
  - host: {{ required "host is required" .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 80
