image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.6.0@sha256:7f0385362022ebddbecec0f00892074623ecd00e0ef93b180d8a4d65b3e8dd20
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
