image:
  repository: ghcr.io/stirling-tools/stirling-pdf
  tag: 2.13.0@sha256:dc2d06bc68bb5a023d3635060ba0070381446bff02011143c7e46ea0c184755c
ingress: {}
auth:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
maxSize: 500m
