apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    {{- if .Values.dashboard.enabled }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* "^/dashboard$") {
        return 302 {{ .Values.dashboard.url }};
      }
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ required "ingress.host is required" .Values.ingress.host }}
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ required "ingress.host is required" .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8100
      - path: /filebrowser
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8080
