apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ required "host is required" .Values.ingress.host }}
    secretName: minecraft-tls
  rules:
  - host: {{ required "host is required" .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minecraft
            port:
              number: 8100
