apiVersion: v1
kind: Secret
metadata:
  name: minecraft
type: Opaque
stringData:
  curseforge-api-key: {{ required "curseforge.apiKey is required" .Values.curseforge.apiKey | quote }}
  rcon-password: {{ required "rcon.password is required" .Values.rcon.password | quote }}
  filebrowser-password: {{ required "filebrowser.password is required" .Values.filebrowser.password | quote }}