apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 25565
      name: server
      protocol: TCP
    - port: 25575
      name: rcon
      protocol: TCP
    - port: 8100
      name: map
      protocol: TCP
    - port: 8080
      name: filebrowser
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      name: metrics
      protocol: TCP
    {{- end }}
  selector:
    app: {{ .Release.Name }}