apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  type: ClusterIP
  ports:
    - port: 25565
      name: minecraft
      protocol: TCP
    - port: 25575
      name: rcon
      protocol: TCP
    - port: 8100
      name: map
      protocol: TCP
    - port: 8080
      name: filebrowser
      protocol: TCP
    - port: 19565
      name: metrics
      protocol: TCP
  selector:
    app: minecraft