apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: ClusterIP
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
    - port: 25575
      targetPort: 25575
      protocol: TCP
  selector:
    app: minecraft