
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minecraft
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: minecraft