image:
  repository: adguard/adguardhome
  tag: v0.107.77@sha256:e6f2b8bcda06064ab055b44933a4f0e983c35558b9cdb8d2e7ab1efcee36d890
  pullPolicy: IfNotPresent
cron: "*/5 * * * *"
runOnStart: false
continueOnError: false
origin:
  url: http://192.168.68.93:58745
  username: "" # Set in pipeline
  password: "" # Set in pipeline
replica:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
  autoSetup: true
syncapi:
  image:
    repository: ghcr.io/bakito/adguardhome-sync
    tag: v0.9.0@sha256:a4e63e705c5602b7bdd5a9554615a78125521273a7aa5da5831517780a06aee4
    pullPolicy: IfNotPresent
  metrics:
    enabled: true
  username: "" # Set in pipeline
  password: "" # Set in pipeline
  darkMode: true
resources:
  adguardhome:
    requests:
      cpu: 30m
      memory: 1Gi
    limits:
      memory: 1Gi
  sync:
    requests:
      cpu: 20m
      memory: 512Mi
    limits:
      memory: 512Mi
