image:
  repository: adguard/adguardhome
  tag: v0.107.78@sha256:1ea34eafe5dc691007946e8eaab7bf46b0de9412f39213d8c06e48b53bf9a6c5
  pullPolicy: IfNotPresent
cron: "*/5 * * * *"
runOnStart: false
continueOnError: false
origin:
  url: http://192.168.68.93:58745
  username: "" # Set in pipeline
  password: "" # Set in pipeline
replica:
  username: "" # Set in pipeline
  password: "" # Set in pipeline
  autoSetup: true
syncapi:
  image:
    repository: ghcr.io/bakito/adguardhome-sync
    tag: v0.9.2@sha256:fb7224aeeab74d68990c3ecf51594a6f92428fcc93c7a162c3bc221e77a49025
    pullPolicy: IfNotPresent
  metrics:
    enabled: true
    queryLogLimit: 100
  username: "" # Set in pipeline
  password: "" # Set in pipeline
  darkMode: true
resources:
  adguardhome:
    requests:
      cpu: 30m
      memory: 1Gi
    limits:
      memory: 1Gi
  sync:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 256Mi
