apiVersion: v1
kind: Secret
metadata:
  name: teslamate
type: Opaque
stringData:
  database-password: {{ required "database.password is required" .Values.database.password | quote }}
  mqtt-password: {{ required "mqtt.password is required" .Values.mqtt.password | quote }}
  encryption-key: {{ required "encryptionKey is required" .Values.encryptionKey | quote }}