{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required "name is required" .Values.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "disk.capacity is required" .Values.disk.capacity }}
  storageClassName: longhorn
  volumeName: {{ required "name is required" .Values.name }}
{{- end }}