apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ required "name is required" .Values.name }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ required "disk.capacity is required" .Values.disk.capacity }}
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    {{- if .Values.volumeHandle }}
    volumeHandle: {{ .Values.volumeHandle }}
    {{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn