metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
influxdb:
  resources:
    requests:
      cpu: 10m
      memory: 200Mi
    limits:
      memory: 200Mi
ingress:
  enabled: true
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
persistence:
  existingClaim: influxdb
