metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
influxdb:
  resources: {} # TODO
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
persistence:
  existingClaim: influxdb