metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
influxdb:
  resources:
    requests:
      cpu: 10m
      memory: 150Mi
    limits:
      memory: 150Mi
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
persistence:
  existingClaim: influxdb
