metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
persistence:
  existingClaim: mongodb
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
