authenticatedEmailsFile:
  enabled: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
  - secretName: oauth2-proxy-tls
config:
  configFile: |-
    email_domains = []
    upstreams = [ "file:///dev/null" ]