metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
primary:
  persistence:
    existingClaim: postgresql
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
