metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
  extraEnvVars:
  - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
    value: "true"
primary:
  persistence:
    existingClaim: postgresql
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
auth:
  database: postgres