env:
  DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
  TZ: Europe/London
service:
  bittorrent:
    enabled: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - paths:
      - path: /
    tls:
    - secretName: qbittorrent-tls
persistence:
  vuetorrent:
    enabled: true
    type: emptyDir
  config:
    enabled: true
    existingClaim: qbittorrent-config
  downloads:
    enabled: true
    existingClaim: qbittorrent-downloads
    mountPath: /downloads