ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
    hosts:
    - paths:
      - path: /
    tls:
    - secretName: sinusbot-tls
resources:
  requests:
    cpu: 15m
    memory: 200Mi
  limits:
    memory: 200Mi
persistence:
  sinusbot:
    enabled: true
    type: pvc
    existingClaim: sinusbot