metrics:
  enabled: true
  prometheusRule:
    enabled: true
  exporter:
    env:
      remote: localhost:10012 # Needs https://github.com/k8s-at-home/charts/pull/1621
env:
  TS3SERVER_DB_PLUGIN: ts3db_mariadb
  TS3SERVER_DB_SQLCREATEPATH: create_mariadb
  TS3SERVER_DB_HOST: mariadb
  TS3SERVER_DB_USER: teamspeak-alt
  TS3SERVER_DB_NAME: teamspeak-alt
  TS3SERVER_DB_WAITUNTILREADY: 30
  TS3SERVER_LICENSE: accept
  TS3SERVER_DEFAULT_VOICE_PORT: 9988
  TS3SERVER_QUERY_PORT: 10012
  TS3SERVER_FILETRANSFER_PORT: 30034
  TS3SERVER_FILETRANSFER_IP: 0.0.0.0
resources:
  requests:
    cpu: 20m
    memory: 30Mi
  limits:
    memory: 30Mi
service:
  main:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
    ports:
      voice:
        port: 9988
      serverquery:
        port: 10012
      filetransfer:
        port: 30034
probes:
  readiness:
    custom: true
    spec:
      tcpSocket:
        port: 10012
  liveness:
    custom: true
    spec:
      tcpSocket:
        port: 10012
  startup:
    custom: true
    spec:
      tcpSocket:
        port: 10012
persistence:
  data:
    enabled: true
    type: pvc
    existingClaim: teamspeak-alt