metrics:
  enabled: true
  prometheusRule:
    enabled: true
env:
  TS3SERVER_DB_PLUGIN: ts3db_mariadb
  TS3SERVER_DB_SQLCREATEPATH: create_mariadb
  TS3SERVER_DB_HOST: mariadb
  TS3SERVER_DB_USER: teamspeak-alt
  TS3SERVER_DB_NAME: teamspeak-alt
  TS3SERVER_DB_WAITUNTILREADY: 30
  TS3SERVER_LICENSE: accept
  TS3SERVER_DEFAULT_VOICE_PORT: 9988
  TS3SERVER_QUERY_PORT: 10012
  TS3SERVER_FILETRANSFER_PORT: 30034
  TS3SERVER_FILETRANSFER_IP: 0.0.0.0
service:
  # Services can be merged in Kubernetes >= 1.24 with feature gate MixedProtocolLBService
  main:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
    ports:
      voice:
        enabled: false
      serverquery:
        port: 10012
      filetransfer:
        port: 30034
  udp:
    enabled: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
    ports:
      voice:
        enabled: true
        port: 9988
        protocol: UDP
persistence:
  data:
    enabled: true
    type: pvc
    existingClaim: teamspeak-alt