image:
  tag: 3.13.7
metrics:
  enabled: true
  prometheusRule:
    enabled: true
env:
  TS3SERVER_DB_PLUGIN: ts3db_sqlite3
  TS3SERVER_DB_SQLCREATEPATH: create_sqlite
  TS3SERVER_LICENSE: accept
resources:
  requests:
    cpu: 20m
    memory: 35Mi
  limits:
    memory: 35Mi
service:
  main:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: abyss
    externalTrafficPolicy: Local
persistence:
  data:
    enabled: true
    type: pvc
    existingClaim: teamspeak