ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - paths:
      - path: /
    tls:
    - secretName: teslamate-tls
env:
  DATABASE_HOST: postgresql
  DATABASE_USER: teslamate
  DATABASE_NAME: teslamate
  TZ: Europe/London
  DISABLE_MQTT: "true"
  LOCALE: en
# TODO RESOURCES
# resources:
#   requests:
#     cpu: 15m
#     memory: 200Mi
#   limits:
#     memory: 200Mi