image:
  repository: teamspeak
  tag: 3.13.8@sha256:15acbc64c92f57ef1fd8dd203791fa7f70a14707e60ee494132f26b5ca265c6b
  pullPolicy: IfNotPresent
ports:
  filetransfer: 30035
  serverquery: 10013
  voice: 9989
persistence:
  existingClaim: teamspeak-old
resources:
  requests:
    cpu: 20m
    memory: 35Mi
  limits:
    memory: 35Mi
