image:
  repository: teamspeak
  tag: 3.13.8@sha256:11fb1dd03c68ae7b3a8a86c5a08827d01d87a833177ad92ee5c19d7b72d08ce0
  pullPolicy: IfNotPresent
ports:
  filetransfer: 30035
  serverquery: 10013
  voice: 9989
persistence:
  existingClaim: teamspeak-old
resources:
  requests:
    cpu: 20m
    memory: 35Mi
  limits:
    memory: 35Mi
