image:
  repository: teamspeak
  tag: 3.13.7@sha256:4d3fa1c0db9a5a4ac69a2d07d6f0478539e464b15e7186c243a9f194bc1141fa
  pullPolicy: IfNotPresent
ports:
  filetransfer: 30035
  serverquery: 10013
  voice: 9989
persistence:
  existingClaim: teamspeak-old
resources:
  requests:
    cpu: 20m
    memory: 35Mi
  limits:
    memory: 35Mi
