apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-account-rclone
type: Opaque
stringData:
  rclone.conf: |
    [azureblob]
    type = azureblob
    account = {{ required "storageAccount.name is required" .Values.storageAccount.name }}
    key = {{ required "storageAccount.key is required" .Values.storageAccount.key }}

    [azureblob-encrypted]
    type = crypt
    remote = azureblob:encrypted
    password = {{ required "crypt.obscuredPassword is required" .Values.crypt.obscuredPassword }}
    password2 = {{ required "crypt.obscuredSalt is required" .Values.crypt.obscuredSalt }}