apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-account
type: Opaque
stringData:
  azurestorageaccountname: {{ required "storageAccount.name is required" .Values.storageAccount.name }}
  azurestorageaccountkey: {{ required "storageAccount.key is required" .Values.storageAccount.key }}
