apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.kubernetes.mattjeanes.com
      secretName: kubernetes-api-tls
  rules:
  - host: api.kubernetes.mattjeanes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes
            port:
              number: 443
