apiVersion: v1
kind: Secret
metadata:
  name: restic-backup-secret
type: Opaque
stringData:
  AZURE_ACCOUNT_NAME: {{ required "storageAccount.name is required" .Values.storageAccount.name | quote }}
  AZURE_ACCOUNT_KEY: {{ required "storageAccount.key is required" .Values.storageAccount.key | quote }}
  RESTIC_PASSWORD: {{ required "resticPassword is required" .Values.resticPassword | quote }}
  RESTIC_REPOSITORY: {{ printf "azure:%s:/" .Values.container | quote }}
