apiVersion: v1
kind: Secret
metadata:
  name: longhorn-azblob-secret
type: Opaque
stringData:
  AZBLOB_ACCOUNT_NAME: {{ required "storageAccount.name is required" .Values.storageAccount.name }}
  AZBLOB_ACCOUNT_KEY: {{ required "storageAccount.key is required" .Values.storageAccount.key }}