apiVersion: v1
kind: Secret
metadata:
  name: longhorn-azblob-secret
spec:
  type: Opaque
  data:
    AZBLOB_ACCOUNT_NAME: {{ .Values.azureBlobStorageAccountName | b64enc | quote }}
    AZBLOB_ACCOUNT_KEY: {{ .Values.azureBlobStorageAccountKey | b64enc | quote }}