apiVersion: v1
kind: Secret
metadata:
  name: azure-cloud-provider
type: Opaque
data:
  cloud-config: {{ printf "{\"tenantId\": \"%s\",\"subscriptionId\": \"%s\",\"aadClientId\": \"%s\",\"aadClientSecret\": \"%s\"}" .Values.azure.tenantId .Values.azure.subscriptionId .Values.azure.aadClientId .Values.azure.aadClientSecret | b64enc }}
