vpa:
  recommender:
    extraArgs:
      prometheus-address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      storage: prometheus
  updater:
    extraArgs:
      min-replicas: "1"
    resources:
      limits:
        cpu: null
  admissionController:
    enabled: true