apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-autoscaler
  namespace: kube-system
data:
  linear: |-
    {
      "nodesPerReplica": 1,
      "min": 1,
      "max": 1,
      "preventSinglePointFailure": true
    }
  ladder: null