postgresql:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
    extraEnvVars:
    - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
      value: "true"
  primary:
    resources:
      requests:
        cpu: 10m
        memory: 750Mi
      limits:
        memory: 750Mi
    persistence:
      existingClaim: postgresql
    service:
      type: NodePort
      externalTrafficPolicy: Local
      nodePorts:
        postgresql: 30002
  auth:
    database: postgres