apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 32400
          hostPort: 32400
          protocol: TCP
        - containerPort: 8324
          hostPort: 8324
          protocol: TCP
        - containerPort: 32410
          hostPort: 32410
          protocol: UDP
        - containerPort: 32412
          hostPort: 32412
          protocol: UDP
        - containerPort: 32413
          hostPort: 32413
          protocol: UDP
        - containerPort: 32414
          hostPort: 32414
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: VERSION
          value: "docker"
        volumeMounts:
        - name: plex-config
          mountPath: /config
        - name: plex-media
          mountPath: /media
        - name: plex-transcoding
          mountPath: /tmp/transcoding
        - name: device-dri
          mountPath: /dev/dri
        - name: device-dvb
          mountPath: /dev/dvb
        securityContext:
          privileged: true
      volumes:
      - name: plex-config
        hostPath:
          path: /mnt/das/Plex
          type: Directory
      - name: plex-media
        hostPath:
          path: /mnt/das/Media
          type: Directory
      - name: plex-transcoding
        hostPath:
          path: /tmp/transcoding
          type: DirectoryOrCreate
      - name: device-dri
        hostPath:
          path: /dev/dri
          type: Directory
      - name: device-dvb
        hostPath:
          path: /dev/dvb
          type: Directory
