apiVersion: v1
kind: Secret
metadata:
  name: adguard-home
type: Opaque
stringData:
  origin-password: {{ required "origin.password is required" .Values.origin.password | quote }}
  replica-password: {{ required "replica.password is required" .Values.replica.password | quote }}
  syncapi-username: {{ required "syncapi.username is required" .Values.syncapi.username | quote }}
  syncapi-password: {{ required "syncapi.password is required" .Values.syncapi.password | quote }}