apiVersion: v1
kind: Secret
metadata:
  name: adguard-home
type: Opaque
stringData:
  origin-password: {{ required "origin.password is required" .Values.origin.password | quote }}
  replica-password: {{ required "replica.password is required" .Values.replica.password | quote }}
  api-password: {{ required "api.password is required" .Values.api.password | quote }}