
{{- if .Values.syncapi.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adguard-home
  labels:
    app: adguard-home
spec:
  endpoints:
  - port: sync-http
    basicAuth:
      username:
        name: adguard-home
        key: syncapi-username
      password:
        name: adguard-home
        key: syncapi-password
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: adguard-home
{{- end }}