apiVersion: v1
kind: Service
metadata:
  name: adguard-home
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns
  selector:
    app: adguard-home