apiVersion: v1
kind: Service
metadata:
  name: adguard-home-external
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns
  selector:
    app: adguard-home
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
spec:
  type: ClusterIP
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: sync-http
  selector:
    app: adguard-home