image:
  repository: ghcr.io/donkie/spoolman
  tag: 0.26.1@sha256:cf9b41e17b93ce7d4ca584d9809142f8918fd290f2cd7d3b8b12ff76c75482f0
ingress: {}
whitelistSourceRange: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16" # Spoolman has no auth; LAN-only
timezone: Europe/London
maxSize: 32m
resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    memory: 256Mi
