image:
  repository: ghcr.io/donkie/spoolman
  tag: 0.27.0@sha256:7aba565eff774c6dda212d4204de8fa30bf68d513127ef875cc7ef3197a4664e
ingress: {}
whitelistSourceRange: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16" # Spoolman has no auth; LAN-only
timezone: Europe/London
maxSize: 32m
resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    memory: 256Mi
