name: AdGuard Home

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'kubernetes/charts/adguard-home/**'
      - '.github/workflows/adguard-home.yaml'

jobs:
  deploy-adguard-home:
    name: Deploy AdGuard Home
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Connect to Kubernetes
        uses: ./.github/actions/connect-k8s
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          hostname: kubernetes-api.${{ vars.HOST }}
          serviceTokenId: ${{ vars.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          serviceTokenSecret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}

      - name: Install adguard home
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            adguard-home . \
            --namespace default \
            -f values.yaml \
            --set origin.username="${{ vars.ADGUARD_ORIGIN_USERNAME }}" \
            --set origin.password="${{ secrets.ADGUARD_ORIGIN_PASSWORD }}" \
            --set replica.username="${{ vars.ADGUARD_REPLICA_USERNAME }}" \
            --set replica.password="${{ secrets.ADGUARD_REPLICA_PASSWORD }}" \
            --set syncapi.username="${{ vars.ADGUARD_SYNCAPI_USERNAME }}" \
            --set syncapi.password="${{ secrets.ADGUARD_SYNCAPI_PASSWORD }}"
        working-directory: kubernetes/charts/adguard-home

      - name: Disconnect from Kubernetes
        uses: ./.github/actions/disconnect-k8s