name: Hello World

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'kubernetes/charts/hello-world/**'
      - '.github/workflows/hello-world.yaml'

jobs:
  deploy-hello-world:
    name: Deploy Hello World
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Connect to Kubernetes
        uses: ./.github/actions/connect-k8s
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          hostname: kubernetes-api.${{ vars.HOST }}
          serviceTokenId: ${{ vars.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          serviceTokenSecret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}

      - name: Install Hello World
        run: |
          helm upgrade --install --wait --atomic --debug \
            hello-world . \
            --namespace default \
            --set host="hello-world-direct.${{ vars.HOST }}"
        working-directory: kubernetes/charts/hello-world

      - name: Wait for hello world certificate to be ready
        uses: ./.github/actions/wait-kube-certificate
        with:
          name: "hello-world-direct-tls"

      - name: Disconnect from Kubernetes
        uses: ./.github/actions/disconnect-k8s