name: Minecraft Forge

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false
  workflow_call:

jobs:
  deploy-minecraft-forge:
    name: Deploy Minecraft Forge
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Connect to Kubernetes
        uses: ./.github/actions/connect-k8s
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          hostname: kubernetes-api.${{ vars.HOST }}
          serviceTokenId: ${{ vars.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          serviceTokenSecret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}

      - name: Install persistent volume for minecraft-forge-server
        run: |
          helm upgrade --install --wait --atomic --debug \
            minecraft-forge-server-persistentvolume . \
            --namespace default \
            --set name=minecraft-forge-server \
            --set disk.capacity=15Gi \
            --set volumeHandle=minecraft-forge-server
        working-directory: kubernetes/charts/longhorn-persistentvolume

      - name: Install persistent volume for minecraft-forge-world
        run: |
          helm upgrade --install --wait --atomic --debug \
            minecraft-forge-world-persistentvolume . \
            --namespace default \
            --set name=minecraft-forge-world \
            --set disk.capacity=15Gi \
            --set volumeHandle=minecraft-forge-world
        working-directory: kubernetes/charts/longhorn-persistentvolume

      - name: Install persistent volume for minecraft-forge-bluemap
        run: |
          helm upgrade --install --wait --atomic --debug \
            minecraft-forge-bluemap-persistentvolume . \
            --namespace default \
            --set name=minecraft-forge-bluemap \
            --set disk.capacity=25Gi \
            --set volumeHandle=minecraft-forge-bluemap
        working-directory: kubernetes/charts/longhorn-persistentvolume

      - name: Install minecraft-forge
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            minecraft-forge . \
            --namespace default \
            --timeout 600s \
            -f values.yaml \
            -f values.forge.yaml \
            --set filebrowser.username='${{ vars.MINECRAFT_FILEBROWSER_USERNAME }}' \
            --set filebrowser.password='${{ secrets.MINECRAFT_FILEBROWSER_PASSWORD }}' \
            --set curseforge.apiKey='${{ secrets.CURSEFORGE_API_KEY }}' \
            --set rcon.password='${{ secrets.MINECRAFT_RCON_PASSWORD }}' \
            --set ingress.host="minecraft-forge.${{ vars.HOST }}" \
            --set debug="${{ github.event.inputs.debug }}"
        working-directory: kubernetes/charts/minecraft

      - name: Disconnect from Kubernetes
        uses: ./.github/actions/disconnect-k8s
