name: Network Infrastructure

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'kubernetes/charts/metallb/**'
      - 'kubernetes/charts/metallb-config/**'
      - '.github/workflows/network-infrastructure.yaml'

jobs:
  deploy-network:
    name: Deploy Network Infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Connect to Kubernetes
        uses: ./.github/actions/connect-k8s
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          hostname: kubernetes-api.${{ vars.HOST }}
          serviceTokenId: ${{ vars.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          serviceTokenSecret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}

      - name: Install metallb
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            metallb . \
            --namespace metallb-system \
            --create-namespace \
            -f values.yaml
        working-directory: kubernetes/charts/metallb

      - name: Install metallb-config
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            metallb-config . \
            --namespace metallb-system \
            --create-namespace \
            -f values.yaml \
            --set ipAddress="${{ vars.LOCAL_IP_ADDRESS }}"
        working-directory: kubernetes/charts/metallb-config

      - name: Disconnect from Kubernetes
        if: always()
        uses: ./.github/actions/disconnect-k8s