name: Plan

on:
  push:
    branches:
      - renovate/*
    paths:
      - terraform/**
  workflow_dispatch:
    inputs:
      runApply:
        description: "Terraform run apply"
        required: true
        default: "false"
  pull_request:
    branches:
      - renovate/*
    paths:
      - terraform/**

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup OpenTofu 
        uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1

      - name: Terraform Init
        run: tofu init -backend-config="storage_account_name=abyssterraform" -backend-config="container_name=terraform" -backend-config="key=terraform.tfstate" -backend-config="access_key=${{ secrets.TERRAFORM_STORAGE_ACCOUNT_KEY }}" -upgrade
        working-directory: terraform

      - name: Set Terraform variables
        run: |
          tee terraform.tfvars <<EOF
          ssh_public_key = "${{ secrets.SSH_PUBLIC_KEY }}"
          cloudflare_api_token = "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          cloudflare_account_id = "${{ vars.CLOUDFLARE_ACCOUNT_ID }}"
          cloudflare_zone_id = "${{ vars.CLOUDFLARE_ZONE_ID }}"
          home_ip = "${{ secrets.HOME_IP }}"
          email = "${{ vars.EMAIL }}"
          windows_server_password = "${{ secrets.WINDOWS_SERVER_PASSWORD }}"
          azure_subscription_id = "${{ vars.AZURE_SUBSCRIPTION_ID }}"
          azure_subscription_id_old = "${{ vars.AZURE_SUBSCRIPTION_ID_OLD }}"
          EOF
        working-directory: terraform

      - name: Terraform Plan
        run: tofu plan -out tfplan
        working-directory: terraform
        env:
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - name: Terraform Validate and Apply
        run: tofu apply tfplan
        working-directory: terraform
        env:
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
        if: github.event.inputs.runApply == 'true'
