# This is a basic workflow to help you get started with Actions

name: Setup Kubernetes Cluster

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v2.1
        with:
          # Resource Group Name
          resource-group: ${{ secrets.KUBERNETES_CLUSTER_RESOURCE_GROUP }}
          # AKS Cluster Name
          cluster-name: ${{ secrets.KUBERNETES_CLUSTER_NAME }}
          
      - name: Install Nginx Ingress
        run: |
          helm upgrade --install --wait --atomic --debug ingress-nginx ingress-nginx \
            --repo https://kubernetes.github.io/ingress-nginx \
            --namespace ingress-nginx --create-namespace
