name: SinusBot

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'kubernetes/charts/sinusbot/**'
      - 'kubernetes/charts/azure-persistentvolume/**'
      - '.github/workflows/sinusbot.yaml'

jobs:
  deploy-sinusbot:
    name: Deploy SinusBot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Connect to Kubernetes
        uses: ./.github/actions/connect-k8s
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          hostname: kubernetes-api.${{ vars.HOST }}
          serviceTokenId: ${{ vars.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          serviceTokenSecret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}

      - name: Install persistent volume for sinusbot
        run: |
          helm upgrade --install --wait --atomic --debug \
            sinusbot-persistentvolume . \
            --namespace default \
            --set name=sinusbot \
            --set disk.capacity=10Gi \
            --set useFileShare=true \
            --set fileShare.name=sinusbot \
            --set fileShare.subscriptionId=${{ vars.AZURE_SUBSCRIPTION_ID }} \
            --set fileShare.uid=1001 \
            --set fileShare.gid=1001
        working-directory: kubernetes/charts/azure-persistentvolume

      - name: Install sinusbot
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            sinusbot . \
            --namespace default \
            -f values.yaml
        working-directory: kubernetes/charts/sinusbot

      - name: Disconnect from Kubernetes
        if: always()
        uses: ./.github/actions/disconnect-k8s