name: Vertical Pod Autoscaler

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'kubernetes/charts/vpa/**'
      - '.github/workflows/vpa.yaml'

jobs:
  deploy-vpa:
    name: Deploy Vertical Pod Autoscaler
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Connect to Kubernetes
        uses: ./.github/actions/connect-k8s
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          hostname: kubernetes-api.${{ vars.HOST }}
          serviceTokenId: ${{ vars.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          serviceTokenSecret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}

      - name: Install vpa
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            vpa . \
            --namespace vpa \
            --create-namespace \
            -f values.yaml
        working-directory: kubernetes/charts/vpa

      - name: Disconnect from Kubernetes
        uses: ./.github/actions/disconnect-k8s