apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.serverquery.http }}
      targetPort: query-http
      protocol: TCP
      name: query-http
  selector:
    app: {{ .Release.Name }}
