apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-proxy-config
data:
  Caddyfile: |
    :80 {
      reverse_proxy 192.168.68.93:8123 {
        trusted_proxies private_ranges
      }
    }