apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-proxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ required "ingress.host is required" .Values.ingress.host | quote }}
      secretName: homeassistant-tls
  rules:
  - host: {{ required "ingress.host is required" .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant-proxy
            port:
              number: 80
