{
 "title": "Energy",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aggregation",
    "label": "Bar chart aggregation",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Solar energy total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_generated_solar_energy_total\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Highest solar day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: 2023-01-30T00:00:00Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_generated_solar_energy_total\")\r\n  |> window(every: 1d)\r\n  |> max()\r\n  |> group()\r\n  |> difference()\r\n  |> sort()\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Highest solar week",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: 2023-01-30T00:00:00Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_generated_solar_energy_total\")\r\n  |> window(every: 1w)\r\n  |> max()\r\n  |> group()\r\n  |> difference()\r\n  |> sort()\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Import from grid total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_import_from_grid_total\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Load total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_local_load_consumption_total\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Export to grid total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_export_to_grid_total\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Battery charged (grid) total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_battery_ac_charged_total\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Battery charged total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_battery_charged_total\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Energy use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Energy use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_local_load_consumption_total\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> increase()\r\n  |> difference()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_local_load_consumption_today"
      }
     ]
    },
    {
     "alias": "Energy use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_battery_ac_charged_total\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> increase()\r\n  |> difference()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_local_load_consumption_today"
      }
     ]
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"stephen_s_room_breaker_today_energy\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> increase()\r\n  |> difference()"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"amy_s_computer_today_s_consumption\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> increase()\r\n  |> difference()"
    },
    {
     "rawSql": "SELECT time, SUM(total_energy_used) AS \"Amy's Tesla\"\r\nFROM (\r\n\tSELECT \r\n\t\t$__timeGroup(date, ${aggregation}) AS time,\r\n\t\tcharging_process_id,\r\n\t\tSUM(energy_used) AS total_energy_used \r\n\tFROM (\r\n\t\tSELECT \r\n\t\t\tcharging_process_id,\r\n\t\t\tCASE\r\n\t\t\t\tWHEN charger_phases IS NULL THEN charger_power\r\n\t\t\t\tELSE charger_actual_current * charger_voltage * CAST(1 AS float) / 1000.0\r\n\t\t\tEND *\r\n\t\t\tEXTRACT(epoch FROM (date - LAG(date) OVER (PARTITION BY charging_process_id ORDER BY date))) / 3600 AS energy_used,\r\n\t\t\tdate\r\n\t\tFROM \r\n\t\t\tcharges\r\n\t\tWHERE \r\n\t\t\t$__timeFilter(date)\r\n\t) t\r\n\tWHERE $__timeFilter(date)\r\n\tGROUP BY time, charging_process_id\r\n\tORDER BY time, charging_process_id\r\n) t2\r\nINNER JOIN charging_processes cp ON t2.charging_process_id = cp.id\r\nWHERE cp.geofence_id = 1\r\nGROUP BY time\r\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"amy_s_laptop_today_s_consumption\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> increase()\r\n  |> difference()"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"lounge_heater_today_s_consumption\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> increase()\r\n  |> difference()"
    }
   ]
  },
  {
   "title": "Battery State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Battery SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "%",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_battery_state_of_charge\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> window(every: v.windowPeriod)\r\n  |> mean()\r\n  |> group()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_battery_state_of_charge"
      }
     ]
    }
   ]
  },
  {
   "title": "Solar energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Solar Input",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_generated_solar_energy_total\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> difference()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "growatt_input_kilowatt_actual" }
     ]
    }
   ]
  },
  {
   "title": "Import / export to grid",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Import from grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "kW",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_import_from_grid_total\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> difference()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_import_from_grid_actual"
      }
     ]
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_export_to_grid_total\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> difference()\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0 }))"
    }
   ]
  },
  {
   "title": "Power output",
   "type": "timeseries",
   "description": "Includes both solar and battery output",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Power output",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kW\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_output_kilowatt_actual\")\r\n  |> window(every: v.windowPeriod)\r\n  |> mean()\r\n  |> group()\r\n  |> fill(value: 0.0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "growatt_output_kilowatt_actual" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kW",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kW\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"growatt_local_load_consumption_actual\")\r\n  |> window(every: v.windowPeriod)\r\n  |> mean()\r\n  |> group()\r\n  |> fill(usePrevious: true)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_local_load_consumption_actual"
      }
     ]
    }
   ]
  },
  {
   "title": "Stephen's energy usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Energy use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"stephen_s_room_breaker_today_energy\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> increase()\r\n  |> difference()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_local_load_consumption_today"
      }
     ]
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"stephen_s_heater_today_s_consumption\")\r\n  |> window(every: ${aggregation})\r\n  |> max()\r\n  |> group()\r\n  |> increase()\r\n  |> difference()"
    }
   ]
  }
 ]
}