{
 "title": "Minecraft Vanilla",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{container=\"minecraft-vanilla\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players (Current)",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "mc_player_online{container=\"minecraft-vanilla\"} == 1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(mc_player_online{container=\"minecraft-vanilla\"})",
     "legendFormat": "Player Count"
    }
   ]
  },
  {
   "title": "Entities (Current)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_entities_total{container=\"minecraft-vanilla\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Chunks Loaded per Dimension (Current)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{container=\"minecraft-vanilla\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"minecraft-vanilla\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"minecraft-vanilla\"}[1m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"minecraft-vanilla\"})",
     "legendFormat": "Pod Memory"
    }
   ]
  },
  {
   "title": "Server Tick Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "mc_tick_duration_average{container=\"minecraft-vanilla\"}",
     "legendFormat": "Tick Duration (Avg)"
    }
   ]
  },
  {
   "title": "Server Tick Duration (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "mc_tick_duration_max{container=\"minecraft-vanilla\"}",
     "legendFormat": "Tick Duration (Max)"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(mc_entities_total{container=\"minecraft-vanilla\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Chunks Loaded per Dimension (Current)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "chunks" } },
   "targets": [
    {
     "expr": "sum(mc_loaded_chunks_total{container=\"minecraft-vanilla\"}) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(mc_jvm_threads_current{container=\"minecraft-vanilla\"})",
     "legendFormat": "Current Threads"
    },
    {
     "expr": "sum(mc_jvm_threads_peak{container=\"minecraft-vanilla\"})",
     "legendFormat": "Peak Threads"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mc_jvm_gc_collection_seconds_sum{gc=\"G1 Concurrent GC\", container=\"minecraft-vanilla\"}[1m]))",
     "legendFormat": "G1 Concurrent GC"
    },
    {
     "expr": "sum(rate(mc_jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\", container=\"minecraft-vanilla\"}[1m]))",
     "legendFormat": "G1 Old Generation"
    },
    {
     "expr": "sum(rate(mc_jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\", container=\"minecraft-vanilla\"}[1m]))",
     "legendFormat": "G1 Young Generation"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(mc_jvm_memory{type=\"max\",container=\"minecraft-vanilla\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(mc_jvm_memory{type=\"free\",container=\"minecraft-vanilla\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(mc_jvm_memory{type=\"allocated\",container=\"minecraft-vanilla\"})",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}